### ISSUE TITLE
Errors while running 

### ISSUE THREAD

**Issue by sthorsen** [JohnBrodie/pyjector#13]
Hi I 'm trying to get your awesome project to work with my Benq MP626. But I bet this errors:

./pyjector_controller benq "/dev/ttyUSB0" power on
Traceback (most recent call last):
  File "./pyjector_controller", line 18, in <module>
    pyjector = Pyjector(port=args.port, device_id=args.device)
  File "/root/pyjector/pyjector/pyjector.py", line 92, in __init__
    self.get_config(device_id, kwargs)
  File "/root/pyjector/pyjector/pyjector.py", line 110, in get_config
    self.available_configs = self._populate_configs()
  File "/root/pyjector/pyjector/pyjector.py", line 142, in _populate_configs
    json_data = json.loads(data.read())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 356 column 6 (char 9289)

I don't have that much experience with python. Du you know if I'm missing something?

**Comment by JohnBrodie** [comment]
I've merged changes from #11 and released a new version, does it work for you now?
